apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config-helm
data:
  AUTH_PUBLIC_KEY: {{ printf "%s" .Values.keys.public_key | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret-helm
type: Opaque
data:
  AUTH_PRIVATE_KEY:  {{ printf "%s" .Values.keys.private_key | b64enc | quote }}