apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config-helm
  namespace: {{ .Values.service.namespace }}
data:
  DB_HOST: {{ printf "%s" (include "postgresql.fullname" .) }}
  DB_PORT: {{ printf "%s" .Values.postgresql.service.port | quote }}
  AUTH_PUBLIC_KEY: {{ printf "%s" .Values.keys.public_key | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret-helm
type: Opaque
data:
  AUTH_PRIVATE_KEY:  {{ printf "%s" .Values.keys.private_key | b64enc | quote }}
  DB_NAME: {{ printf "%s" .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DB_USER: {{ printf "%s" .Values.postgresql.postgresqlUsername  | b64enc | quote }}
  DB_PASSWORD: {{ printf "%s" .Values.postgresql.postgresqlPassword  | b64enc | quote }}