app_name: user-service
image: ekasenya/user-app:v4.1

replicaCount: 2

service:
  name: user-service
  type: NodePort
  port: 80
  namespace: authapp

postgresql:
  enabled: true
  postgresqlUsername: user
  postgresqlPassword: user
  postgresqlDatabase: user-db
  service:
      port: "5432"

job:
  restartPolicy: OnFailure

metrics:
  serviceMonitor:
    enabled: true