app_name: auth-service
image: ekasenya/auth-app:v1.4

replicaCount: 2

service:
  type: NodePort
  port: 9099

job:
  restartPolicy: OnFailure

keys:
  private_key: ""
  public_key: ""

metrics:
  serviceMonitor:
    enabled: true